version: '2'
services:
  app:
    build: .
    image: keboola/db-writer-pgsql
    volumes:
      - .:/code
    working_dir: /code
    command: "./phpunit.sh"
    tty: true
    stdin_open: true
    environment:
      PGSQL_DB_HOST: pgsql
      PGSQL_DB_PORT: 5432
      PGSQL_DB_USER: postgres
      PGSQL_DB_PASSWORD: some password
      PGSQL_DB_DATABASE: postgres
      PGSQL_DB_SCHEMA: public
    links:
      - pgsql
      - sshproxy

  pgsql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: some password

  sshproxy:
    build: ./tests/docker/sshproxy
    volumes:
        - ./tests/docker/sshproxy:/code
    working_dir: /code
    ports:
      - "2222:22"
    links:
      - pgsql

  code-coverage:
    build:
      context: .
      dockerfile: ./tests/docker/code-coverage/Dockerfile
    image: keboola/db-writer-pgsql-code-coverage
    command: "./code-coverage.sh"
    volumes:
      - ./:/code
    environment:
      CODECLIMATE_REPO_TOKEN: $CODECLIMATE_REPO_TOKEN
      PGSQL_DB_HOST: pgsql
      PGSQL_DB_PORT: 5432
      PGSQL_DB_USER: postgres
      PGSQL_DB_PASSWORD: some password
      PGSQL_DB_DATABASE: postgres
      PGSQL_DB_SCHEMA: public
    links:
      - pgsql
      - sshproxy